/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/types`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Buyer-log-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Buyer-sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Farmer-log-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Farmer-sign-up`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/splash`; params?: Router.UnknownOutputParams; } | { pathname: `/types`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Buyer-log-in`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Buyer-sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Farmer-log-in`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Farmer-sign-up`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/splash${`?${string}` | `#${string}` | ''}` | `/types${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/Buyer-log-in${`?${string}` | `#${string}` | ''}` | `/auth/Buyer-sign-up${`?${string}` | `#${string}` | ''}` | `/auth/Farmer-log-in${`?${string}` | `#${string}` | ''}` | `/auth/Farmer-sign-up${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/types`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Buyer-log-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Buyer-sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Farmer-log-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Farmer-sign-up`; params?: Router.UnknownInputParams; };
    }
  }
}
